{% set name = "qttools" %}
{% set version = "6.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: 58e855ad1b2533094726c8a425766b63a04a0eede2ed85086860e54593aa4b2a
    folder: {{ name }}

build:
  number: 0
  skip: True  # [ppc64le or s390x]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libdrm-devel') }}               # [linux]
    - {{ cdt('libglvnd-glx') }}               # [linux and not x86_64]
    - {{ cdt('libglvnd-egl') }}               # [linux and not x86_64]
    - {{ cdt('libice-devel') }}               # [linux]
    - {{ cdt('libsm-devel') }}                # [linux]
    - {{ cdt('libx11-devel') }}               # [linux]
    - {{ cdt('libxau-devel') }}               # [linux]
    - {{ cdt('mesa-libgl-devel') }}           # [linux]
    - {{ cdt('mesa-libgbm') }}                # [linux]
    - {{ cdt('mesa-libegl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}           # [linux]
    - {{ cdt('xcb-util-devel') }}             # [linux]
    - {{ cdt('xcb-util-image-devel') }}       # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}       # [linux]
    - {{ cdt('libselinux') }}                 # [linux]
    - {{ cdt('libxext') }}                    # [linux]
    - {{ cdt('libxdamage') }}                 # [linux]
    - {{ cdt('libxfixes') }}                  # [linux]
    - {{ cdt('libxxf86vm') }}                 # [linux]
    - pkg-config  # [unix]
    - bison       # [linux]
    - flex        # [linux]
    - gperf       # [linux]
    - jom         # [win]
    - m2-bison    # [win]
    - m2-flex     # [win]
    - m2-gperf    # [win]
    - cmake
    - ninja
    - perl

  host:
    - qtbase {{ version }}
    - qtdeclarative {{ version }}
    - zstd

  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

test:
  commands:
    {% for bin in ["Linguist6", "Designer6", "pixeltool6", "Assistant6", "qdistancefieldgenerator6", "qtplugininfo6", "qdbus6", "qdbusviewer6", "qtdiag6"] %}
    - test -e $PREFIX/bin/{{ bin }}                              # [osx]
    - test -e $PREFIX/bin/{{ bin|lower }}                        # [linux]
    - if not exist %PREFIX%\\Library\\bin\\{{ bin }}.exe exit 1  # [win]
    {% endfor %}

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: {{ name }}/LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}
