{% set name = "qttools" %}
{% set version = "6.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: d8b7f7e8e970cc0b975205fd6d5832ea917ef3e751df69b97439c1cddd67a489
    folder: {{ name }}

build:
  number: 1
  # https://doc.qt.io/qt-6/qt-releases.html#binary-compatibility
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config     # [unix]
    - bison          # [linux]
    - flex           # [linux]
    - gperf          # [linux]
    - jom            # [win]
    - msys2-bison    # [win]
    - msys2-flex     # [win]
    - msys2-gperf    # [win]
    - cmake
    - ninja
    - perl
  host:
    - qtbase-devel {{ version }}
    - qtdeclarative {{ version }}
    - zstd {{ zstd }}
    # Vulkan support
    - libvulkan-headers {{ libvulkan }}  # [not osx]
    - libvulkan-loader {{ libvulkan }}   # [not osx]

test:
  commands:
    {% for bin in ["Linguist6", "Designer6", "pixeltool6", "Assistant6", "qdistancefieldgenerator6", "qtplugininfo6", "qdbus6", "qdbusviewer6", "qtdiag6"] %}
    - test -e $PREFIX/bin/{{ bin }}                              # [osx]
    - test -e $PREFIX/bin/{{ bin|lower }}                        # [linux]
    - if not exist %PREFIX%\\Library\\bin\\{{ bin }}.exe exit 1  # [win]
    {% endfor %}

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: {{ name }}/LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}
