{% set name = "qttools" %}
{% set version = "6.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: 90c4a562f4ccfd043fd99f34c600853e0b5ba9babc6ec616c0f306f2ce3f4b4c
    folder: {{ name }}

build:
  number: 0
  skip: True  # [osx and x86_64]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config     # [unix]
    - bison          # [linux]
    - flex           # [linux]
    - gperf          # [linux]
    - jom            # [win]
    - msys2-bison    # [win]
    - msys2-flex     # [win]
    - msys2-gperf    # [win]
    - cmake
    - ninja
    - perl
  host:
    - qtbase-devel {{ version }}
    - qtdeclarative {{ version }}
    - zstd {{ zstd }}
    # Vulkan support
    - libvulkan-headers {{ libvulkan }}  # [linux]
    - libvulkan-loader {{ libvulkan }}   # [linux]
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

test:
  commands:
    {% for bin in ["Linguist6", "Designer6", "pixeltool6", "Assistant6", "qdistancefieldgenerator6", "qtplugininfo6", "qdbus6", "qdbusviewer6", "qtdiag6"] %}
    - test -e $PREFIX/bin/{{ bin }}                              # [osx]
    - test -e $PREFIX/bin/{{ bin|lower }}                        # [linux]
    - if not exist %PREFIX%\\Library\\bin\\{{ bin }}.exe exit 1  # [win]
    {% endfor %}

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: {{ name }}/LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}
